<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>3b4d52ce-a45b-4151-aab3-784c4e436606</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Name is defined 
then
	set decision to `Hello { Name }!` ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
